### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by yangfan0909** [zhouyupeng/webpack4.x_demo#3]
Error: listen EADDRINUSE 127.0.0.1:8888
    at Server.setupListenHandle [as _listen2] (net.js:1336:14)
    at listenInCluster (net.js:1384:12)
    at doListen (net.js:1510:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1363:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

问题场景： cnpm run build 的时候，出现此问题，没有找到方法

**Comment by qiuyu303** [comment]
升级了下babel版本，改动了下配置，可以正常运行了。
